name: Periodical actions


on:
  schedule:
    - cron: "0/5 * * * *"

jobs:
  periodical_actions:
    runs-on: ubuntu-latest
    steps:
      - name: ping app
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-little-frog-754.fly.dev/health
